volumes:
  data:

version: '3.3'
services:
  postgredb:
    container_name: postgredb
    hostname: postgredb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./sql/create-schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  ps_estaleiros_api:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    image: mikemreira/rest-api-ps:latest
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://postgredb:5432/postgres?user=postgres&password=postgres"
    ports:
      - "8080:8080"
    depends_on:
      - postgredb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
