DROP TABLE IF EXISTS Registo;
DROP TABLE IF EXISTS Convite;
DROP TABLE IF EXISTS Papel;
DROP TABLE IF EXISTS Obra;
DROP TABLE IF EXISTS Token;
DROP TABLE IF EXISTS PasswordEsquecida;
DROP TABLE IF EXISTS UtilizadorImagem;
DROP TABLE IF EXISTS Utilizador;