name: Push docker image for React.js

on:
  push:
    branches: [ "main" ]
    paths:
      - 'js/**'

jobs:
  push:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile-js
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/projeto-front-end:1.0.0
